/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMATIC.SDK.Common;
using APIMATIC.SDK.Http.Request;
using APIMATIC.SDK.Http.Response;
using APIMATIC.SDK.Http.Client;

namespace AWSECommerceService.PCL.Controllers
{
    public partial interface IAWSECommerceServiceBindingController
    {
        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartClearResponseMsgModel response from the API call</return>
        Models.CartClearResponseMsgModel CreateCartClear(Models.CartClearRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartClearResponseMsgModel response from the API call</return>
        Task<Models.CartClearResponseMsgModel> CreateCartClearAsync(Models.CartClearRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartModifyResponseMsgModel response from the API call</return>
        Models.CartModifyResponseMsgModel CreateCartModify(Models.CartModifyRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartModifyResponseMsgModel response from the API call</return>
        Task<Models.CartModifyResponseMsgModel> CreateCartModifyAsync(Models.CartModifyRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartCreateResponseMsgModel response from the API call</return>
        Models.CartCreateResponseMsgModel CreateCartCreate(Models.CartCreateRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartCreateResponseMsgModel response from the API call</return>
        Task<Models.CartCreateResponseMsgModel> CreateCartCreateAsync(Models.CartCreateRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartAddResponseMsgModel response from the API call</return>
        Models.CartAddResponseMsgModel CreateCartAdd(Models.CartAddRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartAddResponseMsgModel response from the API call</return>
        Task<Models.CartAddResponseMsgModel> CreateCartAddAsync(Models.CartAddRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartGetResponseMsgModel response from the API call</return>
        Models.CartGetResponseMsgModel CreateCartGet(Models.CartGetRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartGetResponseMsgModel response from the API call</return>
        Task<Models.CartGetResponseMsgModel> CreateCartGetAsync(Models.CartGetRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.SimilarityLookupResponseMsgModel response from the API call</return>
        Models.SimilarityLookupResponseMsgModel CreateSimilarityLookup(Models.SimilarityLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.SimilarityLookupResponseMsgModel response from the API call</return>
        Task<Models.SimilarityLookupResponseMsgModel> CreateSimilarityLookupAsync(Models.SimilarityLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.BrowseNodeLookupResponseMsgModel response from the API call</return>
        Models.BrowseNodeLookupResponseMsgModel CreateBrowseNodeLookup(Models.BrowseNodeLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.BrowseNodeLookupResponseMsgModel response from the API call</return>
        Task<Models.BrowseNodeLookupResponseMsgModel> CreateBrowseNodeLookupAsync(Models.BrowseNodeLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemLookupResponseMsgModel response from the API call</return>
        Models.ItemLookupResponseMsgModel CreateItemLookup(Models.ItemLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemLookupResponseMsgModel response from the API call</return>
        Task<Models.ItemLookupResponseMsgModel> CreateItemLookupAsync(Models.ItemLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemSearchResponseMsgModel response from the API call</return>
        Models.ItemSearchResponseMsgModel CreateItemSearch(Models.ItemSearchRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemSearchResponseMsgModel response from the API call</return>
        Task<Models.ItemSearchResponseMsgModel> CreateItemSearchAsync(Models.ItemSearchRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemSearchResponseMsgModel response from the API call</return>
        Models.ItemSearchResponseMsgModel CreateItemSearch9(Models.ItemSearchRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemSearchResponseMsgModel response from the API call</return>
        Task<Models.ItemSearchResponseMsgModel> CreateItemSearch9Async(Models.ItemSearchRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemLookupResponseMsgModel response from the API call</return>
        Models.ItemLookupResponseMsgModel CreateItemLookup10(Models.ItemLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemLookupResponseMsgModel response from the API call</return>
        Task<Models.ItemLookupResponseMsgModel> CreateItemLookup10Async(Models.ItemLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.BrowseNodeLookupResponseMsgModel response from the API call</return>
        Models.BrowseNodeLookupResponseMsgModel CreateBrowseNodeLookup11(Models.BrowseNodeLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.BrowseNodeLookupResponseMsgModel response from the API call</return>
        Task<Models.BrowseNodeLookupResponseMsgModel> CreateBrowseNodeLookup11Async(Models.BrowseNodeLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.SimilarityLookupResponseMsgModel response from the API call</return>
        Models.SimilarityLookupResponseMsgModel CreateSimilarityLookup12(Models.SimilarityLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.SimilarityLookupResponseMsgModel response from the API call</return>
        Task<Models.SimilarityLookupResponseMsgModel> CreateSimilarityLookup12Async(Models.SimilarityLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartGetResponseMsgModel response from the API call</return>
        Models.CartGetResponseMsgModel CreateCartGet13(Models.CartGetRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartGetResponseMsgModel response from the API call</return>
        Task<Models.CartGetResponseMsgModel> CreateCartGet13Async(Models.CartGetRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartAddResponseMsgModel response from the API call</return>
        Models.CartAddResponseMsgModel CreateCartAdd14(Models.CartAddRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartAddResponseMsgModel response from the API call</return>
        Task<Models.CartAddResponseMsgModel> CreateCartAdd14Async(Models.CartAddRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartCreateResponseMsgModel response from the API call</return>
        Models.CartCreateResponseMsgModel CreateCartCreate15(Models.CartCreateRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartCreateResponseMsgModel response from the API call</return>
        Task<Models.CartCreateResponseMsgModel> CreateCartCreate15Async(Models.CartCreateRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartModifyResponseMsgModel response from the API call</return>
        Models.CartModifyResponseMsgModel CreateCartModify16(Models.CartModifyRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartModifyResponseMsgModel response from the API call</return>
        Task<Models.CartModifyResponseMsgModel> CreateCartModify16Async(Models.CartModifyRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartClearResponseMsgModel response from the API call</return>
        Models.CartClearResponseMsgModel CreateCartClear17(Models.CartClearRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartClearResponseMsgModel response from the API call</return>
        Task<Models.CartClearResponseMsgModel> CreateCartClear17Async(Models.CartClearRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemSearchResponseMsgModel response from the API call</return>
        Models.ItemSearchResponseMsgModel CreateItemSearch18(Models.ItemSearchRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemSearchResponseMsgModel response from the API call</return>
        Task<Models.ItemSearchResponseMsgModel> CreateItemSearch18Async(Models.ItemSearchRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemLookupResponseMsgModel response from the API call</return>
        Models.ItemLookupResponseMsgModel CreateItemLookup19(Models.ItemLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemLookupResponseMsgModel response from the API call</return>
        Task<Models.ItemLookupResponseMsgModel> CreateItemLookup19Async(Models.ItemLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.BrowseNodeLookupResponseMsgModel response from the API call</return>
        Models.BrowseNodeLookupResponseMsgModel CreateBrowseNodeLookup20(Models.BrowseNodeLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.BrowseNodeLookupResponseMsgModel response from the API call</return>
        Task<Models.BrowseNodeLookupResponseMsgModel> CreateBrowseNodeLookup20Async(Models.BrowseNodeLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.SimilarityLookupResponseMsgModel response from the API call</return>
        Models.SimilarityLookupResponseMsgModel CreateSimilarityLookup21(Models.SimilarityLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.SimilarityLookupResponseMsgModel response from the API call</return>
        Task<Models.SimilarityLookupResponseMsgModel> CreateSimilarityLookup21Async(Models.SimilarityLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartGetResponseMsgModel response from the API call</return>
        Models.CartGetResponseMsgModel CreateCartGet22(Models.CartGetRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartGetResponseMsgModel response from the API call</return>
        Task<Models.CartGetResponseMsgModel> CreateCartGet22Async(Models.CartGetRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartAddResponseMsgModel response from the API call</return>
        Models.CartAddResponseMsgModel CreateCartAdd23(Models.CartAddRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartAddResponseMsgModel response from the API call</return>
        Task<Models.CartAddResponseMsgModel> CreateCartAdd23Async(Models.CartAddRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartCreateResponseMsgModel response from the API call</return>
        Models.CartCreateResponseMsgModel CreateCartCreate24(Models.CartCreateRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartCreateResponseMsgModel response from the API call</return>
        Task<Models.CartCreateResponseMsgModel> CreateCartCreate24Async(Models.CartCreateRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartModifyResponseMsgModel response from the API call</return>
        Models.CartModifyResponseMsgModel CreateCartModify25(Models.CartModifyRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartModifyResponseMsgModel response from the API call</return>
        Task<Models.CartModifyResponseMsgModel> CreateCartModify25Async(Models.CartModifyRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartClearResponseMsgModel response from the API call</return>
        Models.CartClearResponseMsgModel CreateCartClear26(Models.CartClearRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartClearResponseMsgModel response from the API call</return>
        Task<Models.CartClearResponseMsgModel> CreateCartClear26Async(Models.CartClearRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemSearchResponseMsgModel response from the API call</return>
        Models.ItemSearchResponseMsgModel CreateItemSearch27(Models.ItemSearchRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemSearchResponseMsgModel response from the API call</return>
        Task<Models.ItemSearchResponseMsgModel> CreateItemSearch27Async(Models.ItemSearchRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemLookupResponseMsgModel response from the API call</return>
        Models.ItemLookupResponseMsgModel CreateItemLookup28(Models.ItemLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemLookupResponseMsgModel response from the API call</return>
        Task<Models.ItemLookupResponseMsgModel> CreateItemLookup28Async(Models.ItemLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.BrowseNodeLookupResponseMsgModel response from the API call</return>
        Models.BrowseNodeLookupResponseMsgModel CreateBrowseNodeLookup29(Models.BrowseNodeLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.BrowseNodeLookupResponseMsgModel response from the API call</return>
        Task<Models.BrowseNodeLookupResponseMsgModel> CreateBrowseNodeLookup29Async(Models.BrowseNodeLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.SimilarityLookupResponseMsgModel response from the API call</return>
        Models.SimilarityLookupResponseMsgModel CreateSimilarityLookup30(Models.SimilarityLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.SimilarityLookupResponseMsgModel response from the API call</return>
        Task<Models.SimilarityLookupResponseMsgModel> CreateSimilarityLookup30Async(Models.SimilarityLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartGetResponseMsgModel response from the API call</return>
        Models.CartGetResponseMsgModel CreateCartGet31(Models.CartGetRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartGetResponseMsgModel response from the API call</return>
        Task<Models.CartGetResponseMsgModel> CreateCartGet31Async(Models.CartGetRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartAddResponseMsgModel response from the API call</return>
        Models.CartAddResponseMsgModel CreateCartAdd32(Models.CartAddRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartAddResponseMsgModel response from the API call</return>
        Task<Models.CartAddResponseMsgModel> CreateCartAdd32Async(Models.CartAddRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartCreateResponseMsgModel response from the API call</return>
        Models.CartCreateResponseMsgModel CreateCartCreate33(Models.CartCreateRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartCreateResponseMsgModel response from the API call</return>
        Task<Models.CartCreateResponseMsgModel> CreateCartCreate33Async(Models.CartCreateRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartModifyResponseMsgModel response from the API call</return>
        Models.CartModifyResponseMsgModel CreateCartModify34(Models.CartModifyRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartModifyResponseMsgModel response from the API call</return>
        Task<Models.CartModifyResponseMsgModel> CreateCartModify34Async(Models.CartModifyRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartClearResponseMsgModel response from the API call</return>
        Models.CartClearResponseMsgModel CreateCartClear35(Models.CartClearRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartClearResponseMsgModel response from the API call</return>
        Task<Models.CartClearResponseMsgModel> CreateCartClear35Async(Models.CartClearRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemSearchResponseMsgModel response from the API call</return>
        Models.ItemSearchResponseMsgModel CreateItemSearch36(Models.ItemSearchRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemSearchResponseMsgModel response from the API call</return>
        Task<Models.ItemSearchResponseMsgModel> CreateItemSearch36Async(Models.ItemSearchRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemLookupResponseMsgModel response from the API call</return>
        Models.ItemLookupResponseMsgModel CreateItemLookup37(Models.ItemLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemLookupResponseMsgModel response from the API call</return>
        Task<Models.ItemLookupResponseMsgModel> CreateItemLookup37Async(Models.ItemLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.BrowseNodeLookupResponseMsgModel response from the API call</return>
        Models.BrowseNodeLookupResponseMsgModel CreateBrowseNodeLookup38(Models.BrowseNodeLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.BrowseNodeLookupResponseMsgModel response from the API call</return>
        Task<Models.BrowseNodeLookupResponseMsgModel> CreateBrowseNodeLookup38Async(Models.BrowseNodeLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.SimilarityLookupResponseMsgModel response from the API call</return>
        Models.SimilarityLookupResponseMsgModel CreateSimilarityLookup39(Models.SimilarityLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.SimilarityLookupResponseMsgModel response from the API call</return>
        Task<Models.SimilarityLookupResponseMsgModel> CreateSimilarityLookup39Async(Models.SimilarityLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartGetResponseMsgModel response from the API call</return>
        Models.CartGetResponseMsgModel CreateCartGet40(Models.CartGetRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartGetResponseMsgModel response from the API call</return>
        Task<Models.CartGetResponseMsgModel> CreateCartGet40Async(Models.CartGetRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartAddResponseMsgModel response from the API call</return>
        Models.CartAddResponseMsgModel CreateCartAdd41(Models.CartAddRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartAddResponseMsgModel response from the API call</return>
        Task<Models.CartAddResponseMsgModel> CreateCartAdd41Async(Models.CartAddRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartCreateResponseMsgModel response from the API call</return>
        Models.CartCreateResponseMsgModel CreateCartCreate42(Models.CartCreateRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartCreateResponseMsgModel response from the API call</return>
        Task<Models.CartCreateResponseMsgModel> CreateCartCreate42Async(Models.CartCreateRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartModifyResponseMsgModel response from the API call</return>
        Models.CartModifyResponseMsgModel CreateCartModify43(Models.CartModifyRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartModifyResponseMsgModel response from the API call</return>
        Task<Models.CartModifyResponseMsgModel> CreateCartModify43Async(Models.CartModifyRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartClearResponseMsgModel response from the API call</return>
        Models.CartClearResponseMsgModel CreateCartClear44(Models.CartClearRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartClearResponseMsgModel response from the API call</return>
        Task<Models.CartClearResponseMsgModel> CreateCartClear44Async(Models.CartClearRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemSearchResponseMsgModel response from the API call</return>
        Models.ItemSearchResponseMsgModel CreateItemSearch45(Models.ItemSearchRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemSearchResponseMsgModel response from the API call</return>
        Task<Models.ItemSearchResponseMsgModel> CreateItemSearch45Async(Models.ItemSearchRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemLookupResponseMsgModel response from the API call</return>
        Models.ItemLookupResponseMsgModel CreateItemLookup46(Models.ItemLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemLookupResponseMsgModel response from the API call</return>
        Task<Models.ItemLookupResponseMsgModel> CreateItemLookup46Async(Models.ItemLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.BrowseNodeLookupResponseMsgModel response from the API call</return>
        Models.BrowseNodeLookupResponseMsgModel CreateBrowseNodeLookup47(Models.BrowseNodeLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.BrowseNodeLookupResponseMsgModel response from the API call</return>
        Task<Models.BrowseNodeLookupResponseMsgModel> CreateBrowseNodeLookup47Async(Models.BrowseNodeLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.SimilarityLookupResponseMsgModel response from the API call</return>
        Models.SimilarityLookupResponseMsgModel CreateSimilarityLookup48(Models.SimilarityLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.SimilarityLookupResponseMsgModel response from the API call</return>
        Task<Models.SimilarityLookupResponseMsgModel> CreateSimilarityLookup48Async(Models.SimilarityLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartGetResponseMsgModel response from the API call</return>
        Models.CartGetResponseMsgModel CreateCartGet49(Models.CartGetRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartGetResponseMsgModel response from the API call</return>
        Task<Models.CartGetResponseMsgModel> CreateCartGet49Async(Models.CartGetRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartAddResponseMsgModel response from the API call</return>
        Models.CartAddResponseMsgModel CreateCartAdd50(Models.CartAddRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartAddResponseMsgModel response from the API call</return>
        Task<Models.CartAddResponseMsgModel> CreateCartAdd50Async(Models.CartAddRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartCreateResponseMsgModel response from the API call</return>
        Models.CartCreateResponseMsgModel CreateCartCreate51(Models.CartCreateRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartCreateResponseMsgModel response from the API call</return>
        Task<Models.CartCreateResponseMsgModel> CreateCartCreate51Async(Models.CartCreateRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartModifyResponseMsgModel response from the API call</return>
        Models.CartModifyResponseMsgModel CreateCartModify52(Models.CartModifyRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartModifyResponseMsgModel response from the API call</return>
        Task<Models.CartModifyResponseMsgModel> CreateCartModify52Async(Models.CartModifyRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartClearResponseMsgModel response from the API call</return>
        Models.CartClearResponseMsgModel CreateCartClear53(Models.CartClearRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartClearResponseMsgModel response from the API call</return>
        Task<Models.CartClearResponseMsgModel> CreateCartClear53Async(Models.CartClearRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemSearchResponseMsgModel response from the API call</return>
        Models.ItemSearchResponseMsgModel CreateItemSearch54(Models.ItemSearchRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemSearchResponseMsgModel response from the API call</return>
        Task<Models.ItemSearchResponseMsgModel> CreateItemSearch54Async(Models.ItemSearchRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemLookupResponseMsgModel response from the API call</return>
        Models.ItemLookupResponseMsgModel CreateItemLookup55(Models.ItemLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemLookupResponseMsgModel response from the API call</return>
        Task<Models.ItemLookupResponseMsgModel> CreateItemLookup55Async(Models.ItemLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.BrowseNodeLookupResponseMsgModel response from the API call</return>
        Models.BrowseNodeLookupResponseMsgModel CreateBrowseNodeLookup56(Models.BrowseNodeLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.BrowseNodeLookupResponseMsgModel response from the API call</return>
        Task<Models.BrowseNodeLookupResponseMsgModel> CreateBrowseNodeLookup56Async(Models.BrowseNodeLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.SimilarityLookupResponseMsgModel response from the API call</return>
        Models.SimilarityLookupResponseMsgModel CreateSimilarityLookup57(Models.SimilarityLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.SimilarityLookupResponseMsgModel response from the API call</return>
        Task<Models.SimilarityLookupResponseMsgModel> CreateSimilarityLookup57Async(Models.SimilarityLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartGetResponseMsgModel response from the API call</return>
        Models.CartGetResponseMsgModel CreateCartGet58(Models.CartGetRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartGetResponseMsgModel response from the API call</return>
        Task<Models.CartGetResponseMsgModel> CreateCartGet58Async(Models.CartGetRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartAddResponseMsgModel response from the API call</return>
        Models.CartAddResponseMsgModel CreateCartAdd59(Models.CartAddRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartAddResponseMsgModel response from the API call</return>
        Task<Models.CartAddResponseMsgModel> CreateCartAdd59Async(Models.CartAddRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartCreateResponseMsgModel response from the API call</return>
        Models.CartCreateResponseMsgModel CreateCartCreate60(Models.CartCreateRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartCreateResponseMsgModel response from the API call</return>
        Task<Models.CartCreateResponseMsgModel> CreateCartCreate60Async(Models.CartCreateRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartModifyResponseMsgModel response from the API call</return>
        Models.CartModifyResponseMsgModel CreateCartModify61(Models.CartModifyRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartModifyResponseMsgModel response from the API call</return>
        Task<Models.CartModifyResponseMsgModel> CreateCartModify61Async(Models.CartModifyRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartClearResponseMsgModel response from the API call</return>
        Models.CartClearResponseMsgModel CreateCartClear62(Models.CartClearRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartClearResponseMsgModel response from the API call</return>
        Task<Models.CartClearResponseMsgModel> CreateCartClear62Async(Models.CartClearRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemSearchResponseMsgModel response from the API call</return>
        Models.ItemSearchResponseMsgModel CreateItemSearch63(Models.ItemSearchRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemSearchResponseMsgModel response from the API call</return>
        Task<Models.ItemSearchResponseMsgModel> CreateItemSearch63Async(Models.ItemSearchRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemLookupResponseMsgModel response from the API call</return>
        Models.ItemLookupResponseMsgModel CreateItemLookup64(Models.ItemLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemLookupResponseMsgModel response from the API call</return>
        Task<Models.ItemLookupResponseMsgModel> CreateItemLookup64Async(Models.ItemLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.BrowseNodeLookupResponseMsgModel response from the API call</return>
        Models.BrowseNodeLookupResponseMsgModel CreateBrowseNodeLookup65(Models.BrowseNodeLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.BrowseNodeLookupResponseMsgModel response from the API call</return>
        Task<Models.BrowseNodeLookupResponseMsgModel> CreateBrowseNodeLookup65Async(Models.BrowseNodeLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.SimilarityLookupResponseMsgModel response from the API call</return>
        Models.SimilarityLookupResponseMsgModel CreateSimilarityLookup66(Models.SimilarityLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.SimilarityLookupResponseMsgModel response from the API call</return>
        Task<Models.SimilarityLookupResponseMsgModel> CreateSimilarityLookup66Async(Models.SimilarityLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartGetResponseMsgModel response from the API call</return>
        Models.CartGetResponseMsgModel CreateCartGet67(Models.CartGetRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartGetResponseMsgModel response from the API call</return>
        Task<Models.CartGetResponseMsgModel> CreateCartGet67Async(Models.CartGetRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartAddResponseMsgModel response from the API call</return>
        Models.CartAddResponseMsgModel CreateCartAdd68(Models.CartAddRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartAddResponseMsgModel response from the API call</return>
        Task<Models.CartAddResponseMsgModel> CreateCartAdd68Async(Models.CartAddRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartCreateResponseMsgModel response from the API call</return>
        Models.CartCreateResponseMsgModel CreateCartCreate69(Models.CartCreateRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartCreateResponseMsgModel response from the API call</return>
        Task<Models.CartCreateResponseMsgModel> CreateCartCreate69Async(Models.CartCreateRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartModifyResponseMsgModel response from the API call</return>
        Models.CartModifyResponseMsgModel CreateCartModify70(Models.CartModifyRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartModifyResponseMsgModel response from the API call</return>
        Task<Models.CartModifyResponseMsgModel> CreateCartModify70Async(Models.CartModifyRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartClearResponseMsgModel response from the API call</return>
        Models.CartClearResponseMsgModel CreateCartClear71(Models.CartClearRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartClearResponseMsgModel response from the API call</return>
        Task<Models.CartClearResponseMsgModel> CreateCartClear71Async(Models.CartClearRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemSearchResponseMsgModel response from the API call</return>
        Models.ItemSearchResponseMsgModel CreateItemSearch72(Models.ItemSearchRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemSearchResponseMsgModel response from the API call</return>
        Task<Models.ItemSearchResponseMsgModel> CreateItemSearch72Async(Models.ItemSearchRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemLookupResponseMsgModel response from the API call</return>
        Models.ItemLookupResponseMsgModel CreateItemLookup73(Models.ItemLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemLookupResponseMsgModel response from the API call</return>
        Task<Models.ItemLookupResponseMsgModel> CreateItemLookup73Async(Models.ItemLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.BrowseNodeLookupResponseMsgModel response from the API call</return>
        Models.BrowseNodeLookupResponseMsgModel CreateBrowseNodeLookup74(Models.BrowseNodeLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.BrowseNodeLookupResponseMsgModel response from the API call</return>
        Task<Models.BrowseNodeLookupResponseMsgModel> CreateBrowseNodeLookup74Async(Models.BrowseNodeLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.SimilarityLookupResponseMsgModel response from the API call</return>
        Models.SimilarityLookupResponseMsgModel CreateSimilarityLookup75(Models.SimilarityLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.SimilarityLookupResponseMsgModel response from the API call</return>
        Task<Models.SimilarityLookupResponseMsgModel> CreateSimilarityLookup75Async(Models.SimilarityLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartGetResponseMsgModel response from the API call</return>
        Models.CartGetResponseMsgModel CreateCartGet76(Models.CartGetRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartGetResponseMsgModel response from the API call</return>
        Task<Models.CartGetResponseMsgModel> CreateCartGet76Async(Models.CartGetRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartAddResponseMsgModel response from the API call</return>
        Models.CartAddResponseMsgModel CreateCartAdd77(Models.CartAddRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartAddResponseMsgModel response from the API call</return>
        Task<Models.CartAddResponseMsgModel> CreateCartAdd77Async(Models.CartAddRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartCreateResponseMsgModel response from the API call</return>
        Models.CartCreateResponseMsgModel CreateCartCreate78(Models.CartCreateRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartCreateResponseMsgModel response from the API call</return>
        Task<Models.CartCreateResponseMsgModel> CreateCartCreate78Async(Models.CartCreateRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartModifyResponseMsgModel response from the API call</return>
        Models.CartModifyResponseMsgModel CreateCartModify79(Models.CartModifyRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartModifyResponseMsgModel response from the API call</return>
        Task<Models.CartModifyResponseMsgModel> CreateCartModify79Async(Models.CartModifyRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartClearResponseMsgModel response from the API call</return>
        Models.CartClearResponseMsgModel CreateCartClear80(Models.CartClearRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartClearResponseMsgModel response from the API call</return>
        Task<Models.CartClearResponseMsgModel> CreateCartClear80Async(Models.CartClearRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemSearchResponseMsgModel response from the API call</return>
        Models.ItemSearchResponseMsgModel CreateItemSearch81(Models.ItemSearchRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemSearchResponseMsgModel response from the API call</return>
        Task<Models.ItemSearchResponseMsgModel> CreateItemSearch81Async(Models.ItemSearchRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemLookupResponseMsgModel response from the API call</return>
        Models.ItemLookupResponseMsgModel CreateItemLookup82(Models.ItemLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemLookupResponseMsgModel response from the API call</return>
        Task<Models.ItemLookupResponseMsgModel> CreateItemLookup82Async(Models.ItemLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.BrowseNodeLookupResponseMsgModel response from the API call</return>
        Models.BrowseNodeLookupResponseMsgModel CreateBrowseNodeLookup83(Models.BrowseNodeLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.BrowseNodeLookupResponseMsgModel response from the API call</return>
        Task<Models.BrowseNodeLookupResponseMsgModel> CreateBrowseNodeLookup83Async(Models.BrowseNodeLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.SimilarityLookupResponseMsgModel response from the API call</return>
        Models.SimilarityLookupResponseMsgModel CreateSimilarityLookup84(Models.SimilarityLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.SimilarityLookupResponseMsgModel response from the API call</return>
        Task<Models.SimilarityLookupResponseMsgModel> CreateSimilarityLookup84Async(Models.SimilarityLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartGetResponseMsgModel response from the API call</return>
        Models.CartGetResponseMsgModel CreateCartGet85(Models.CartGetRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartGetResponseMsgModel response from the API call</return>
        Task<Models.CartGetResponseMsgModel> CreateCartGet85Async(Models.CartGetRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartAddResponseMsgModel response from the API call</return>
        Models.CartAddResponseMsgModel CreateCartAdd86(Models.CartAddRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartAddResponseMsgModel response from the API call</return>
        Task<Models.CartAddResponseMsgModel> CreateCartAdd86Async(Models.CartAddRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartCreateResponseMsgModel response from the API call</return>
        Models.CartCreateResponseMsgModel CreateCartCreate87(Models.CartCreateRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartCreateResponseMsgModel response from the API call</return>
        Task<Models.CartCreateResponseMsgModel> CreateCartCreate87Async(Models.CartCreateRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartModifyResponseMsgModel response from the API call</return>
        Models.CartModifyResponseMsgModel CreateCartModify88(Models.CartModifyRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartModifyResponseMsgModel response from the API call</return>
        Task<Models.CartModifyResponseMsgModel> CreateCartModify88Async(Models.CartModifyRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartClearResponseMsgModel response from the API call</return>
        Models.CartClearResponseMsgModel CreateCartClear89(Models.CartClearRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartClearResponseMsgModel response from the API call</return>
        Task<Models.CartClearResponseMsgModel> CreateCartClear89Async(Models.CartClearRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemSearchResponseMsgModel response from the API call</return>
        Models.ItemSearchResponseMsgModel CreateItemSearch90(Models.ItemSearchRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemSearchResponseMsgModel response from the API call</return>
        Task<Models.ItemSearchResponseMsgModel> CreateItemSearch90Async(Models.ItemSearchRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemLookupResponseMsgModel response from the API call</return>
        Models.ItemLookupResponseMsgModel CreateItemLookup91(Models.ItemLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.ItemLookupResponseMsgModel response from the API call</return>
        Task<Models.ItemLookupResponseMsgModel> CreateItemLookup91Async(Models.ItemLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.BrowseNodeLookupResponseMsgModel response from the API call</return>
        Models.BrowseNodeLookupResponseMsgModel CreateBrowseNodeLookup92(Models.BrowseNodeLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.BrowseNodeLookupResponseMsgModel response from the API call</return>
        Task<Models.BrowseNodeLookupResponseMsgModel> CreateBrowseNodeLookup92Async(Models.BrowseNodeLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.SimilarityLookupResponseMsgModel response from the API call</return>
        Models.SimilarityLookupResponseMsgModel CreateSimilarityLookup93(Models.SimilarityLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.SimilarityLookupResponseMsgModel response from the API call</return>
        Task<Models.SimilarityLookupResponseMsgModel> CreateSimilarityLookup93Async(Models.SimilarityLookupRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartGetResponseMsgModel response from the API call</return>
        Models.CartGetResponseMsgModel CreateCartGet94(Models.CartGetRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartGetResponseMsgModel response from the API call</return>
        Task<Models.CartGetResponseMsgModel> CreateCartGet94Async(Models.CartGetRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartAddResponseMsgModel response from the API call</return>
        Models.CartAddResponseMsgModel CreateCartAdd95(Models.CartAddRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartAddResponseMsgModel response from the API call</return>
        Task<Models.CartAddResponseMsgModel> CreateCartAdd95Async(Models.CartAddRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartCreateResponseMsgModel response from the API call</return>
        Models.CartCreateResponseMsgModel CreateCartCreate96(Models.CartCreateRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartCreateResponseMsgModel response from the API call</return>
        Task<Models.CartCreateResponseMsgModel> CreateCartCreate96Async(Models.CartCreateRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartModifyResponseMsgModel response from the API call</return>
        Models.CartModifyResponseMsgModel CreateCartModify97(Models.CartModifyRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartModifyResponseMsgModel response from the API call</return>
        Task<Models.CartModifyResponseMsgModel> CreateCartModify97Async(Models.CartModifyRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartClearResponseMsgModel response from the API call</return>
        Models.CartClearResponseMsgModel CreateCartClear98(Models.CartClearRequestMsgModel body);

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CartClearResponseMsgModel response from the API call</return>
        Task<Models.CartClearResponseMsgModel> CreateCartClear98Async(Models.CartClearRequestMsgModel body);

    }
} 