/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;

namespace AWSECommerceService.PCL.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum AudienceRatingEnum
    {
        G, //TODO: Write general description for this method
        PG, //TODO: Write general description for this method
        PG13, //TODO: Write general description for this method
        R, //TODO: Write general description for this method
        NC17, //TODO: Write general description for this method
        NR, //TODO: Write general description for this method
        UNRATED, //TODO: Write general description for this method
        ENUM_6, //TODO: Write general description for this method
        ENUM_12, //TODO: Write general description for this method
        ENUM_16, //TODO: Write general description for this method
        ENUM_18, //TODO: Write general description for this method
        FAMILYVIEWING, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type AudienceRatingEnum
    /// </summary>
    public static class AudienceRatingEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "G", "PG", "PG-13", "R", "NC-17", "NR", "Unrated", "6", "12", "16", "18", "FamilyViewing" };

        /// <summary>
        /// Converts a AudienceRatingEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The AudienceRatingEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(AudienceRatingEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case AudienceRatingEnum.G:
                case AudienceRatingEnum.PG:
                case AudienceRatingEnum.PG13:
                case AudienceRatingEnum.R:
                case AudienceRatingEnum.NC17:
                case AudienceRatingEnum.NR:
                case AudienceRatingEnum.UNRATED:
                case AudienceRatingEnum.ENUM_6:
                case AudienceRatingEnum.ENUM_12:
                case AudienceRatingEnum.ENUM_16:
                case AudienceRatingEnum.ENUM_18:
                case AudienceRatingEnum.FAMILYVIEWING:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of AudienceRatingEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of AudienceRatingEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<AudienceRatingEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into AudienceRatingEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed AudienceRatingEnum value</returns>
        public static AudienceRatingEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type AudienceRatingEnum", value));

            return (AudienceRatingEnum) index;
        }
    }
} 