/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class AvailabilityAttributesModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string availabilityType;
        private bool? isPreorder;
        private int? minimumHours;
        private int? maximumHours;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("AvailabilityType")]
        public string AvailabilityType 
        { 
            get 
            {
                return this.availabilityType; 
            } 
            set 
            {
                this.availabilityType = value;
                onPropertyChanged("AvailabilityType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("IsPreorder")]
        public bool? IsPreorder 
        { 
            get 
            {
                return this.isPreorder; 
            } 
            set 
            {
                this.isPreorder = value;
                onPropertyChanged("IsPreorder");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("MinimumHours")]
        public int? MinimumHours 
        { 
            get 
            {
                return this.minimumHours; 
            } 
            set 
            {
                this.minimumHours = value;
                onPropertyChanged("MinimumHours");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("MaximumHours")]
        public int? MaximumHours 
        { 
            get 
            {
                return this.maximumHours; 
            } 
            set 
            {
                this.maximumHours = value;
                onPropertyChanged("MaximumHours");
            }
        }
    }
} 