/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class BinModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string binName;
        private int binItemCount;
        private Models.BinParameterModel binParameter;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BinName")]
        public string BinName 
        { 
            get 
            {
                return this.binName; 
            } 
            set 
            {
                this.binName = value;
                onPropertyChanged("BinName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BinItemCount")]
        public int BinItemCount 
        { 
            get 
            {
                return this.binItemCount; 
            } 
            set 
            {
                this.binItemCount = value;
                onPropertyChanged("BinItemCount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BinParameter")]
        public Models.BinParameterModel BinParameter 
        { 
            get 
            {
                return this.binParameter; 
            } 
            set 
            {
                this.binParameter = value;
                onPropertyChanged("BinParameter");
            }
        }
    }
} 