/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class BrowseNodeLookupRequestModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private List<string> browseNodeId;
        private List<string> responseGroup;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BrowseNodeId")]
        public List<string> BrowseNodeId 
        { 
            get 
            {
                return this.browseNodeId; 
            } 
            set 
            {
                this.browseNodeId = value;
                onPropertyChanged("BrowseNodeId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ResponseGroup")]
        public List<string> ResponseGroup 
        { 
            get 
            {
                return this.responseGroup; 
            } 
            set 
            {
                this.responseGroup = value;
                onPropertyChanged("ResponseGroup");
            }
        }
    }
} 