/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class BrowseNodeModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.PropertiesModel properties;
        private Models.ChildrenModel children;
        private Models.AncestorsModel ancestors;
        private Models.TopSellersModel topSellers;
        private Models.NewReleasesModel newReleases;
        private string browseNodeId;
        private string name;
        private bool? isCategoryRoot;
        private List<Models.TopItemSetModel> topItemSet;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Properties")]
        public Models.PropertiesModel Properties 
        { 
            get 
            {
                return this.properties; 
            } 
            set 
            {
                this.properties = value;
                onPropertyChanged("Properties");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Children")]
        public Models.ChildrenModel Children 
        { 
            get 
            {
                return this.children; 
            } 
            set 
            {
                this.children = value;
                onPropertyChanged("Children");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Ancestors")]
        public Models.AncestorsModel Ancestors 
        { 
            get 
            {
                return this.ancestors; 
            } 
            set 
            {
                this.ancestors = value;
                onPropertyChanged("Ancestors");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("TopSellers")]
        public Models.TopSellersModel TopSellers 
        { 
            get 
            {
                return this.topSellers; 
            } 
            set 
            {
                this.topSellers = value;
                onPropertyChanged("TopSellers");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("NewReleases")]
        public Models.NewReleasesModel NewReleases 
        { 
            get 
            {
                return this.newReleases; 
            } 
            set 
            {
                this.newReleases = value;
                onPropertyChanged("NewReleases");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BrowseNodeId")]
        public string BrowseNodeId 
        { 
            get 
            {
                return this.browseNodeId; 
            } 
            set 
            {
                this.browseNodeId = value;
                onPropertyChanged("BrowseNodeId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("IsCategoryRoot")]
        public bool? IsCategoryRoot 
        { 
            get 
            {
                return this.isCategoryRoot; 
            } 
            set 
            {
                this.isCategoryRoot = value;
                onPropertyChanged("IsCategoryRoot");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("TopItemSet")]
        public List<Models.TopItemSetModel> TopItemSet 
        { 
            get 
            {
                return this.topItemSet; 
            } 
            set 
            {
                this.topItemSet = value;
                onPropertyChanged("TopItemSet");
            }
        }
    }
} 