/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class CartModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string cartId;
        private string hMAC;
        private string uRLEncodedHMAC;
        private Models.RequestModel request;
        private string purchaseURL;
        private string mobileCartURL;
        private Models.PriceModel subTotal;
        private Models.CartItemsModel cartItems;
        private Models.SavedForLaterItemsModel savedForLaterItems;
        private Models.SimilarProductsModel similarProducts;
        private Models.TopSellersModel topSellers;
        private Models.NewReleasesModel newReleases;
        private Models.SimilarViewedProductsModel similarViewedProducts;
        private Models.OtherCategoriesSimilarProductsModel otherCategoriesSimilarProducts;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CartId")]
        public string CartId 
        { 
            get 
            {
                return this.cartId; 
            } 
            set 
            {
                this.cartId = value;
                onPropertyChanged("CartId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("HMAC")]
        public string HMAC 
        { 
            get 
            {
                return this.hMAC; 
            } 
            set 
            {
                this.hMAC = value;
                onPropertyChanged("HMAC");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("URLEncodedHMAC")]
        public string URLEncodedHMAC 
        { 
            get 
            {
                return this.uRLEncodedHMAC; 
            } 
            set 
            {
                this.uRLEncodedHMAC = value;
                onPropertyChanged("URLEncodedHMAC");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Request")]
        public Models.RequestModel Request 
        { 
            get 
            {
                return this.request; 
            } 
            set 
            {
                this.request = value;
                onPropertyChanged("Request");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("PurchaseURL")]
        public string PurchaseURL 
        { 
            get 
            {
                return this.purchaseURL; 
            } 
            set 
            {
                this.purchaseURL = value;
                onPropertyChanged("PurchaseURL");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("MobileCartURL")]
        public string MobileCartURL 
        { 
            get 
            {
                return this.mobileCartURL; 
            } 
            set 
            {
                this.mobileCartURL = value;
                onPropertyChanged("MobileCartURL");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SubTotal")]
        public Models.PriceModel SubTotal 
        { 
            get 
            {
                return this.subTotal; 
            } 
            set 
            {
                this.subTotal = value;
                onPropertyChanged("SubTotal");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CartItems")]
        public Models.CartItemsModel CartItems 
        { 
            get 
            {
                return this.cartItems; 
            } 
            set 
            {
                this.cartItems = value;
                onPropertyChanged("CartItems");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SavedForLaterItems")]
        public Models.SavedForLaterItemsModel SavedForLaterItems 
        { 
            get 
            {
                return this.savedForLaterItems; 
            } 
            set 
            {
                this.savedForLaterItems = value;
                onPropertyChanged("SavedForLaterItems");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SimilarProducts")]
        public Models.SimilarProductsModel SimilarProducts 
        { 
            get 
            {
                return this.similarProducts; 
            } 
            set 
            {
                this.similarProducts = value;
                onPropertyChanged("SimilarProducts");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("TopSellers")]
        public Models.TopSellersModel TopSellers 
        { 
            get 
            {
                return this.topSellers; 
            } 
            set 
            {
                this.topSellers = value;
                onPropertyChanged("TopSellers");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("NewReleases")]
        public Models.NewReleasesModel NewReleases 
        { 
            get 
            {
                return this.newReleases; 
            } 
            set 
            {
                this.newReleases = value;
                onPropertyChanged("NewReleases");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SimilarViewedProducts")]
        public Models.SimilarViewedProductsModel SimilarViewedProducts 
        { 
            get 
            {
                return this.similarViewedProducts; 
            } 
            set 
            {
                this.similarViewedProducts = value;
                onPropertyChanged("SimilarViewedProducts");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("OtherCategoriesSimilarProducts")]
        public Models.OtherCategoriesSimilarProductsModel OtherCategoriesSimilarProducts 
        { 
            get 
            {
                return this.otherCategoriesSimilarProducts; 
            } 
            set 
            {
                this.otherCategoriesSimilarProducts = value;
                onPropertyChanged("OtherCategoriesSimilarProducts");
            }
        }
    }
} 