/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class CartItemModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string cartItemId;
        private string quantity;
        private Models.MetaDataModel metaData;
        private Models.PriceModel price;
        private string aSIN;
        private string sellerNickname;
        private string title;
        private string productGroup;
        private Models.PriceModel itemTotal;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CartItemId")]
        public string CartItemId 
        { 
            get 
            {
                return this.cartItemId; 
            } 
            set 
            {
                this.cartItemId = value;
                onPropertyChanged("CartItemId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Quantity")]
        public string Quantity 
        { 
            get 
            {
                return this.quantity; 
            } 
            set 
            {
                this.quantity = value;
                onPropertyChanged("Quantity");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("MetaData")]
        public Models.MetaDataModel MetaData 
        { 
            get 
            {
                return this.metaData; 
            } 
            set 
            {
                this.metaData = value;
                onPropertyChanged("MetaData");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Price")]
        public Models.PriceModel Price 
        { 
            get 
            {
                return this.price; 
            } 
            set 
            {
                this.price = value;
                onPropertyChanged("Price");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ASIN")]
        public string ASIN 
        { 
            get 
            {
                return this.aSIN; 
            } 
            set 
            {
                this.aSIN = value;
                onPropertyChanged("ASIN");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SellerNickname")]
        public string SellerNickname 
        { 
            get 
            {
                return this.sellerNickname; 
            } 
            set 
            {
                this.sellerNickname = value;
                onPropertyChanged("SellerNickname");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Title")]
        public string Title 
        { 
            get 
            {
                return this.title; 
            } 
            set 
            {
                this.title = value;
                onPropertyChanged("Title");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ProductGroup")]
        public string ProductGroup 
        { 
            get 
            {
                return this.productGroup; 
            } 
            set 
            {
                this.productGroup = value;
                onPropertyChanged("ProductGroup");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ItemTotal")]
        public Models.PriceModel ItemTotal 
        { 
            get 
            {
                return this.itemTotal; 
            } 
            set 
            {
                this.itemTotal = value;
                onPropertyChanged("ItemTotal");
            }
        }
    }
} 