/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class CollectionSummaryModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.PriceModel lowestListPrice;
        private Models.PriceModel highestListPrice;
        private Models.PriceModel lowestSalePrice;
        private Models.PriceModel highestSalePrice;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("LowestListPrice")]
        public Models.PriceModel LowestListPrice 
        { 
            get 
            {
                return this.lowestListPrice; 
            } 
            set 
            {
                this.lowestListPrice = value;
                onPropertyChanged("LowestListPrice");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("HighestListPrice")]
        public Models.PriceModel HighestListPrice 
        { 
            get 
            {
                return this.highestListPrice; 
            } 
            set 
            {
                this.highestListPrice = value;
                onPropertyChanged("HighestListPrice");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("LowestSalePrice")]
        public Models.PriceModel LowestSalePrice 
        { 
            get 
            {
                return this.lowestSalePrice; 
            } 
            set 
            {
                this.lowestSalePrice = value;
                onPropertyChanged("LowestSalePrice");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("HighestSalePrice")]
        public Models.PriceModel HighestSalePrice 
        { 
            get 
            {
                return this.highestSalePrice; 
            } 
            set 
            {
                this.highestSalePrice = value;
                onPropertyChanged("HighestSalePrice");
            }
        }
    }
} 