/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class CollectionModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.CollectionSummaryModel collectionSummary;
        private Models.CollectionParentModel collectionParent;
        private Models.CollectionItemModel collectionItem;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CollectionSummary")]
        public Models.CollectionSummaryModel CollectionSummary 
        { 
            get 
            {
                return this.collectionSummary; 
            } 
            set 
            {
                this.collectionSummary = value;
                onPropertyChanged("CollectionSummary");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CollectionParent")]
        public Models.CollectionParentModel CollectionParent 
        { 
            get 
            {
                return this.collectionParent; 
            } 
            set 
            {
                this.collectionParent = value;
                onPropertyChanged("CollectionParent");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CollectionItem")]
        public Models.CollectionItemModel CollectionItem 
        { 
            get 
            {
                return this.collectionItem; 
            } 
            set 
            {
                this.collectionItem = value;
                onPropertyChanged("CollectionItem");
            }
        }
    }
} 