/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;

namespace AWSECommerceService.PCL.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum ConditionEnum
    {
        ALL, //TODO: Write general description for this method
        NEW, //TODO: Write general description for this method
        USED, //TODO: Write general description for this method
        COLLECTIBLE, //TODO: Write general description for this method
        REFURBISHED, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type ConditionEnum
    /// </summary>
    public static class ConditionEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "All", "New", "Used", "Collectible", "Refurbished" };

        /// <summary>
        /// Converts a ConditionEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The ConditionEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(ConditionEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case ConditionEnum.ALL:
                case ConditionEnum.NEW:
                case ConditionEnum.USED:
                case ConditionEnum.COLLECTIBLE:
                case ConditionEnum.REFURBISHED:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of ConditionEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of ConditionEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<ConditionEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into ConditionEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed ConditionEnum value</returns>
        public static ConditionEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type ConditionEnum", value));

            return (ConditionEnum) index;
        }
    }
} 