/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class CustomerReviewsModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string iFrameURL;
        private bool? hasReviews;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("IFrameURL")]
        public string IFrameURL 
        { 
            get 
            {
                return this.iFrameURL; 
            } 
            set 
            {
                this.iFrameURL = value;
                onPropertyChanged("IFrameURL");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("HasReviews")]
        public bool? HasReviews 
        { 
            get 
            {
                return this.hasReviews; 
            } 
            set 
            {
                this.hasReviews = value;
                onPropertyChanged("HasReviews");
            }
        }
    }
} 