/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class DiscModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int number;
        private Models.TrackModel track;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Number")]
        public int Number 
        { 
            get 
            {
                return this.number; 
            } 
            set 
            {
                this.number = value;
                onPropertyChanged("Number");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Track")]
        public Models.TrackModel Track 
        { 
            get 
            {
                return this.track; 
            } 
            set 
            {
                this.track = value;
                onPropertyChanged("Track");
            }
        }
    }
} 