/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class EditorialReviewModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string source;
        private string content;
        private bool? isLinkSuppressed;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Source")]
        public string Source 
        { 
            get 
            {
                return this.source; 
            } 
            set 
            {
                this.source = value;
                onPropertyChanged("Source");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Content")]
        public string Content 
        { 
            get 
            {
                return this.content; 
            } 
            set 
            {
                this.content = value;
                onPropertyChanged("Content");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("IsLinkSuppressed")]
        public bool? IsLinkSuppressed 
        { 
            get 
            {
                return this.isLinkSuppressed; 
            } 
            set 
            {
                this.isLinkSuppressed = value;
                onPropertyChanged("IsLinkSuppressed");
            }
        }
    }
} 