/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;

namespace AWSECommerceService.PCL.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum IdTypeEnum
    {
        ASIN, //TODO: Write general description for this method
        UPC, //TODO: Write general description for this method
        SKU, //TODO: Write general description for this method
        EAN, //TODO: Write general description for this method
        ISBN, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type IdTypeEnum
    /// </summary>
    public static class IdTypeEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "ASIN", "UPC", "SKU", "EAN", "ISBN" };

        /// <summary>
        /// Converts a IdTypeEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The IdTypeEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(IdTypeEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case IdTypeEnum.ASIN:
                case IdTypeEnum.UPC:
                case IdTypeEnum.SKU:
                case IdTypeEnum.EAN:
                case IdTypeEnum.ISBN:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of IdTypeEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of IdTypeEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<IdTypeEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into IdTypeEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed IdTypeEnum value</returns>
        public static IdTypeEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type IdTypeEnum", value));

            return (IdTypeEnum) index;
        }
    }
} 