/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class ImageSetModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string category;
        private Models.ImageModel swatchImage;
        private Models.ImageModel smallImage;
        private Models.ImageModel thumbnailImage;
        private Models.ImageModel tinyImage;
        private Models.ImageModel mediumImage;
        private Models.ImageModel largeImage;
        private Models.ImageModel hiResImage;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Category")]
        public string Category 
        { 
            get 
            {
                return this.category; 
            } 
            set 
            {
                this.category = value;
                onPropertyChanged("Category");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SwatchImage")]
        public Models.ImageModel SwatchImage 
        { 
            get 
            {
                return this.swatchImage; 
            } 
            set 
            {
                this.swatchImage = value;
                onPropertyChanged("SwatchImage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SmallImage")]
        public Models.ImageModel SmallImage 
        { 
            get 
            {
                return this.smallImage; 
            } 
            set 
            {
                this.smallImage = value;
                onPropertyChanged("SmallImage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ThumbnailImage")]
        public Models.ImageModel ThumbnailImage 
        { 
            get 
            {
                return this.thumbnailImage; 
            } 
            set 
            {
                this.thumbnailImage = value;
                onPropertyChanged("ThumbnailImage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("TinyImage")]
        public Models.ImageModel TinyImage 
        { 
            get 
            {
                return this.tinyImage; 
            } 
            set 
            {
                this.tinyImage = value;
                onPropertyChanged("TinyImage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("MediumImage")]
        public Models.ImageModel MediumImage 
        { 
            get 
            {
                return this.mediumImage; 
            } 
            set 
            {
                this.mediumImage = value;
                onPropertyChanged("MediumImage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("LargeImage")]
        public Models.ImageModel LargeImage 
        { 
            get 
            {
                return this.largeImage; 
            } 
            set 
            {
                this.largeImage = value;
                onPropertyChanged("LargeImage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("HiResImage")]
        public Models.ImageModel HiResImage 
        { 
            get 
            {
                return this.hiResImage; 
            } 
            set 
            {
                this.hiResImage = value;
                onPropertyChanged("HiResImage");
            }
        }
    }
} 