/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class ImageModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string uRL;
        private Models.DecimalWithUnitsModel height;
        private Models.DecimalWithUnitsModel width;
        private string isVerified;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("URL")]
        public string URL 
        { 
            get 
            {
                return this.uRL; 
            } 
            set 
            {
                this.uRL = value;
                onPropertyChanged("URL");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Height")]
        public Models.DecimalWithUnitsModel Height 
        { 
            get 
            {
                return this.height; 
            } 
            set 
            {
                this.height = value;
                onPropertyChanged("Height");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Width")]
        public Models.DecimalWithUnitsModel Width 
        { 
            get 
            {
                return this.width; 
            } 
            set 
            {
                this.width = value;
                onPropertyChanged("Width");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("IsVerified")]
        public string IsVerified 
        { 
            get 
            {
                return this.isVerified; 
            } 
            set 
            {
                this.isVerified = value;
                onPropertyChanged("IsVerified");
            }
        }
    }
} 