/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class ItemSearchRequestModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.AvailabilityEnum availability;
        private string actor;
        private string artist;
        private List<Models.AudienceRatingEnum> audienceRating;
        private string author;
        private string brand;
        private string browseNode;
        private string composer;
        private Models.ConditionEnum? condition;
        private string conductor;
        private string director;
        private int? itemPage;
        private string keywords;
        private string manufacturer;
        private int? maximumPrice;
        private string merchantId;
        private int? minimumPrice;
        private int? minPercentageOff;
        private string musicLabel;
        private string orchestra;
        private string power;
        private string publisher;
        private string relatedItemPage;
        private List<string> relationshipType;
        private List<string> responseGroup;
        private string searchIndex;
        private string sort;
        private string title;
        private string releaseDate;
        private string includeReviewsSummary;
        private int? truncateReviewsAt;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Availability", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.AvailabilityEnum Availability 
        { 
            get 
            {
                return this.availability; 
            } 
            set 
            {
                this.availability = value;
                onPropertyChanged("Availability");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Actor")]
        public string Actor 
        { 
            get 
            {
                return this.actor; 
            } 
            set 
            {
                this.actor = value;
                onPropertyChanged("Actor");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Artist")]
        public string Artist 
        { 
            get 
            {
                return this.artist; 
            } 
            set 
            {
                this.artist = value;
                onPropertyChanged("Artist");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("AudienceRating", ItemConverterType = typeof(StringValuedEnumConverter))]
        public List<Models.AudienceRatingEnum> AudienceRating 
        { 
            get 
            {
                return this.audienceRating; 
            } 
            set 
            {
                this.audienceRating = value;
                onPropertyChanged("AudienceRating");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Author")]
        public string Author 
        { 
            get 
            {
                return this.author; 
            } 
            set 
            {
                this.author = value;
                onPropertyChanged("Author");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Brand")]
        public string Brand 
        { 
            get 
            {
                return this.brand; 
            } 
            set 
            {
                this.brand = value;
                onPropertyChanged("Brand");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BrowseNode")]
        public string BrowseNode 
        { 
            get 
            {
                return this.browseNode; 
            } 
            set 
            {
                this.browseNode = value;
                onPropertyChanged("BrowseNode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Composer")]
        public string Composer 
        { 
            get 
            {
                return this.composer; 
            } 
            set 
            {
                this.composer = value;
                onPropertyChanged("Composer");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Condition", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.ConditionEnum? Condition 
        { 
            get 
            {
                return this.condition; 
            } 
            set 
            {
                this.condition = value;
                onPropertyChanged("Condition");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Conductor")]
        public string Conductor 
        { 
            get 
            {
                return this.conductor; 
            } 
            set 
            {
                this.conductor = value;
                onPropertyChanged("Conductor");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Director")]
        public string Director 
        { 
            get 
            {
                return this.director; 
            } 
            set 
            {
                this.director = value;
                onPropertyChanged("Director");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ItemPage")]
        public int? ItemPage 
        { 
            get 
            {
                return this.itemPage; 
            } 
            set 
            {
                this.itemPage = value;
                onPropertyChanged("ItemPage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Keywords")]
        public string Keywords 
        { 
            get 
            {
                return this.keywords; 
            } 
            set 
            {
                this.keywords = value;
                onPropertyChanged("Keywords");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Manufacturer")]
        public string Manufacturer 
        { 
            get 
            {
                return this.manufacturer; 
            } 
            set 
            {
                this.manufacturer = value;
                onPropertyChanged("Manufacturer");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("MaximumPrice")]
        public int? MaximumPrice 
        { 
            get 
            {
                return this.maximumPrice; 
            } 
            set 
            {
                this.maximumPrice = value;
                onPropertyChanged("MaximumPrice");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("MerchantId")]
        public string MerchantId 
        { 
            get 
            {
                return this.merchantId; 
            } 
            set 
            {
                this.merchantId = value;
                onPropertyChanged("MerchantId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("MinimumPrice")]
        public int? MinimumPrice 
        { 
            get 
            {
                return this.minimumPrice; 
            } 
            set 
            {
                this.minimumPrice = value;
                onPropertyChanged("MinimumPrice");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("MinPercentageOff")]
        public int? MinPercentageOff 
        { 
            get 
            {
                return this.minPercentageOff; 
            } 
            set 
            {
                this.minPercentageOff = value;
                onPropertyChanged("MinPercentageOff");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("MusicLabel")]
        public string MusicLabel 
        { 
            get 
            {
                return this.musicLabel; 
            } 
            set 
            {
                this.musicLabel = value;
                onPropertyChanged("MusicLabel");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Orchestra")]
        public string Orchestra 
        { 
            get 
            {
                return this.orchestra; 
            } 
            set 
            {
                this.orchestra = value;
                onPropertyChanged("Orchestra");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Power")]
        public string Power 
        { 
            get 
            {
                return this.power; 
            } 
            set 
            {
                this.power = value;
                onPropertyChanged("Power");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Publisher")]
        public string Publisher 
        { 
            get 
            {
                return this.publisher; 
            } 
            set 
            {
                this.publisher = value;
                onPropertyChanged("Publisher");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("RelatedItemPage")]
        public string RelatedItemPage 
        { 
            get 
            {
                return this.relatedItemPage; 
            } 
            set 
            {
                this.relatedItemPage = value;
                onPropertyChanged("RelatedItemPage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("RelationshipType")]
        public List<string> RelationshipType 
        { 
            get 
            {
                return this.relationshipType; 
            } 
            set 
            {
                this.relationshipType = value;
                onPropertyChanged("RelationshipType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ResponseGroup")]
        public List<string> ResponseGroup 
        { 
            get 
            {
                return this.responseGroup; 
            } 
            set 
            {
                this.responseGroup = value;
                onPropertyChanged("ResponseGroup");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SearchIndex")]
        public string SearchIndex 
        { 
            get 
            {
                return this.searchIndex; 
            } 
            set 
            {
                this.searchIndex = value;
                onPropertyChanged("SearchIndex");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Sort")]
        public string Sort 
        { 
            get 
            {
                return this.sort; 
            } 
            set 
            {
                this.sort = value;
                onPropertyChanged("Sort");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Title")]
        public string Title 
        { 
            get 
            {
                return this.title; 
            } 
            set 
            {
                this.title = value;
                onPropertyChanged("Title");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ReleaseDate")]
        public string ReleaseDate 
        { 
            get 
            {
                return this.releaseDate; 
            } 
            set 
            {
                this.releaseDate = value;
                onPropertyChanged("ReleaseDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("IncludeReviewsSummary")]
        public string IncludeReviewsSummary 
        { 
            get 
            {
                return this.includeReviewsSummary; 
            } 
            set 
            {
                this.includeReviewsSummary = value;
                onPropertyChanged("IncludeReviewsSummary");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("TruncateReviewsAt")]
        public int? TruncateReviewsAt 
        { 
            get 
            {
                return this.truncateReviewsAt; 
            } 
            set 
            {
                this.truncateReviewsAt = value;
                onPropertyChanged("TruncateReviewsAt");
            }
        }
    }
} 