/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class ItemLookupModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string marketplaceDomain;
        private string aWSAccessKeyId;
        private string associateTag;
        private string validate;
        private string xMLEscaping;
        private Models.ItemLookupRequestModel shared;
        private List<Models.ItemLookupRequestModel> request;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("MarketplaceDomain")]
        public string MarketplaceDomain 
        { 
            get 
            {
                return this.marketplaceDomain; 
            } 
            set 
            {
                this.marketplaceDomain = value;
                onPropertyChanged("MarketplaceDomain");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("AWSAccessKeyId")]
        public string AWSAccessKeyId 
        { 
            get 
            {
                return this.aWSAccessKeyId; 
            } 
            set 
            {
                this.aWSAccessKeyId = value;
                onPropertyChanged("AWSAccessKeyId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("AssociateTag")]
        public string AssociateTag 
        { 
            get 
            {
                return this.associateTag; 
            } 
            set 
            {
                this.associateTag = value;
                onPropertyChanged("AssociateTag");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Validate")]
        public string Validate 
        { 
            get 
            {
                return this.validate; 
            } 
            set 
            {
                this.validate = value;
                onPropertyChanged("Validate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("XMLEscaping")]
        public string XMLEscaping 
        { 
            get 
            {
                return this.xMLEscaping; 
            } 
            set 
            {
                this.xMLEscaping = value;
                onPropertyChanged("XMLEscaping");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Shared")]
        public Models.ItemLookupRequestModel Shared 
        { 
            get 
            {
                return this.shared; 
            } 
            set 
            {
                this.shared = value;
                onPropertyChanged("Shared");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Request")]
        public List<Models.ItemLookupRequestModel> Request 
        { 
            get 
            {
                return this.request; 
            } 
            set 
            {
                this.request = value;
                onPropertyChanged("Request");
            }
        }
    }
} 