/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class ItemDimensionsModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.DecimalWithUnitsModel height;
        private Models.DecimalWithUnitsModel length;
        private Models.DecimalWithUnitsModel weight;
        private Models.DecimalWithUnitsModel width;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Height")]
        public Models.DecimalWithUnitsModel Height 
        { 
            get 
            {
                return this.height; 
            } 
            set 
            {
                this.height = value;
                onPropertyChanged("Height");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Length")]
        public Models.DecimalWithUnitsModel Length 
        { 
            get 
            {
                return this.length; 
            } 
            set 
            {
                this.length = value;
                onPropertyChanged("Length");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Weight")]
        public Models.DecimalWithUnitsModel Weight 
        { 
            get 
            {
                return this.weight; 
            } 
            set 
            {
                this.weight = value;
                onPropertyChanged("Weight");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Width")]
        public Models.DecimalWithUnitsModel Width 
        { 
            get 
            {
                return this.width; 
            } 
            set 
            {
                this.width = value;
                onPropertyChanged("Width");
            }
        }
    }
} 