/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class ItemLinkModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string description;
        private string uRL;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Description")]
        public string Description 
        { 
            get 
            {
                return this.description; 
            } 
            set 
            {
                this.description = value;
                onPropertyChanged("Description");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("URL")]
        public string URL 
        { 
            get 
            {
                return this.uRL; 
            } 
            set 
            {
                this.uRL = value;
                onPropertyChanged("URL");
            }
        }
    }
} 