/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class ItemAttributesModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.AudienceRatingEnum audienceRating;
        private Models.CatalogNumberListModel catalogNumberList;
        private Models.CreatorModel creator;
        private Models.EANListModel eANList;
        private Models.ItemDimensionsModel itemDimensions;
        private Models.LanguagesModel languages;
        private Models.PackageDimensionsModel packageDimensions;
        private Models.UPCListModel uPCList;
        private List<string> actor;
        private List<string> artist;
        private string aspectRatio;
        private List<string> audioFormat;
        private List<string> author;
        private string binding;
        private string brand;
        private List<string> category;
        private string cEROAgeRating;
        private string clothingSize;
        private string color;
        private string department;
        private List<string> director;
        private string eAN;
        private string edition;
        private List<string> eISBN;
        private string energyEfficiencyClass;
        private string episodeSequence;
        private string eSRBAgeRating;
        private List<string> feature;
        private List<string> format;
        private string genre;
        private string hardwarePlatform;
        private string hazardousMaterialType;
        private bool? isAdultProduct;
        private bool? isAutographed;
        private string iSBN;
        private bool? isEligibleForTradeIn;
        private bool? isMemorabilia;
        private string issuesPerYear;
        private string itemPartNumber;
        private string label;
        private string legalDisclaimer;
        private Models.PriceModel listPrice;
        private string magazineType;
        private string manufacturer;
        private Models.DecimalWithUnitsModel manufacturerMaximumAge;
        private Models.DecimalWithUnitsModel manufacturerMinimumAge;
        private string manufacturerPartsWarrantyDescription;
        private string mediaType;
        private string model;
        private int? modelYear;
        private string mPN;
        private int? numberOfDiscs;
        private int? numberOfIssues;
        private int? numberOfItems;
        private int? numberOfPages;
        private int? numberOfTracks;
        private string operatingSystem;
        private int? packageQuantity;
        private string partNumber;
        private List<string> pictureFormat;
        private List<string> platform;
        private string productGroup;
        private string productTypeName;
        private string productTypeSubcategory;
        private string publicationDate;
        private string publisher;
        private string regionCode;
        private string releaseDate;
        private string seasonSequence;
        private Models.DecimalWithUnitsModel runningTime;
        private string seikodoProductCode;
        private string size;
        private string sKU;
        private string studio;
        private Models.NonNegativeIntegerWithUnitsModel subscriptionLength;
        private string title;
        private string trackSequence;
        private Models.PriceModel tradeInValue;
        private string uPC;
        private string warranty;
        private Models.PriceModel wEEETaxValue;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("AudienceRating", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.AudienceRatingEnum AudienceRating 
        { 
            get 
            {
                return this.audienceRating; 
            } 
            set 
            {
                this.audienceRating = value;
                onPropertyChanged("AudienceRating");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CatalogNumberList")]
        public Models.CatalogNumberListModel CatalogNumberList 
        { 
            get 
            {
                return this.catalogNumberList; 
            } 
            set 
            {
                this.catalogNumberList = value;
                onPropertyChanged("CatalogNumberList");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Creator")]
        public Models.CreatorModel Creator 
        { 
            get 
            {
                return this.creator; 
            } 
            set 
            {
                this.creator = value;
                onPropertyChanged("Creator");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("EANList")]
        public Models.EANListModel EANList 
        { 
            get 
            {
                return this.eANList; 
            } 
            set 
            {
                this.eANList = value;
                onPropertyChanged("EANList");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ItemDimensions")]
        public Models.ItemDimensionsModel ItemDimensions 
        { 
            get 
            {
                return this.itemDimensions; 
            } 
            set 
            {
                this.itemDimensions = value;
                onPropertyChanged("ItemDimensions");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Languages")]
        public Models.LanguagesModel Languages 
        { 
            get 
            {
                return this.languages; 
            } 
            set 
            {
                this.languages = value;
                onPropertyChanged("Languages");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("PackageDimensions")]
        public Models.PackageDimensionsModel PackageDimensions 
        { 
            get 
            {
                return this.packageDimensions; 
            } 
            set 
            {
                this.packageDimensions = value;
                onPropertyChanged("PackageDimensions");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("UPCList")]
        public Models.UPCListModel UPCList 
        { 
            get 
            {
                return this.uPCList; 
            } 
            set 
            {
                this.uPCList = value;
                onPropertyChanged("UPCList");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Actor")]
        public List<string> Actor 
        { 
            get 
            {
                return this.actor; 
            } 
            set 
            {
                this.actor = value;
                onPropertyChanged("Actor");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Artist")]
        public List<string> Artist 
        { 
            get 
            {
                return this.artist; 
            } 
            set 
            {
                this.artist = value;
                onPropertyChanged("Artist");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("AspectRatio")]
        public string AspectRatio 
        { 
            get 
            {
                return this.aspectRatio; 
            } 
            set 
            {
                this.aspectRatio = value;
                onPropertyChanged("AspectRatio");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("AudioFormat")]
        public List<string> AudioFormat 
        { 
            get 
            {
                return this.audioFormat; 
            } 
            set 
            {
                this.audioFormat = value;
                onPropertyChanged("AudioFormat");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Author")]
        public List<string> Author 
        { 
            get 
            {
                return this.author; 
            } 
            set 
            {
                this.author = value;
                onPropertyChanged("Author");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Binding")]
        public string Binding 
        { 
            get 
            {
                return this.binding; 
            } 
            set 
            {
                this.binding = value;
                onPropertyChanged("Binding");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Brand")]
        public string Brand 
        { 
            get 
            {
                return this.brand; 
            } 
            set 
            {
                this.brand = value;
                onPropertyChanged("Brand");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Category")]
        public List<string> Category 
        { 
            get 
            {
                return this.category; 
            } 
            set 
            {
                this.category = value;
                onPropertyChanged("Category");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CEROAgeRating")]
        public string CEROAgeRating 
        { 
            get 
            {
                return this.cEROAgeRating; 
            } 
            set 
            {
                this.cEROAgeRating = value;
                onPropertyChanged("CEROAgeRating");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ClothingSize")]
        public string ClothingSize 
        { 
            get 
            {
                return this.clothingSize; 
            } 
            set 
            {
                this.clothingSize = value;
                onPropertyChanged("ClothingSize");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Color")]
        public string Color 
        { 
            get 
            {
                return this.color; 
            } 
            set 
            {
                this.color = value;
                onPropertyChanged("Color");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Department")]
        public string Department 
        { 
            get 
            {
                return this.department; 
            } 
            set 
            {
                this.department = value;
                onPropertyChanged("Department");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Director")]
        public List<string> Director 
        { 
            get 
            {
                return this.director; 
            } 
            set 
            {
                this.director = value;
                onPropertyChanged("Director");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("EAN")]
        public string EAN 
        { 
            get 
            {
                return this.eAN; 
            } 
            set 
            {
                this.eAN = value;
                onPropertyChanged("EAN");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Edition")]
        public string Edition 
        { 
            get 
            {
                return this.edition; 
            } 
            set 
            {
                this.edition = value;
                onPropertyChanged("Edition");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("EISBN")]
        public List<string> EISBN 
        { 
            get 
            {
                return this.eISBN; 
            } 
            set 
            {
                this.eISBN = value;
                onPropertyChanged("EISBN");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("EnergyEfficiencyClass")]
        public string EnergyEfficiencyClass 
        { 
            get 
            {
                return this.energyEfficiencyClass; 
            } 
            set 
            {
                this.energyEfficiencyClass = value;
                onPropertyChanged("EnergyEfficiencyClass");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("EpisodeSequence")]
        public string EpisodeSequence 
        { 
            get 
            {
                return this.episodeSequence; 
            } 
            set 
            {
                this.episodeSequence = value;
                onPropertyChanged("EpisodeSequence");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ESRBAgeRating")]
        public string ESRBAgeRating 
        { 
            get 
            {
                return this.eSRBAgeRating; 
            } 
            set 
            {
                this.eSRBAgeRating = value;
                onPropertyChanged("ESRBAgeRating");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Feature")]
        public List<string> Feature 
        { 
            get 
            {
                return this.feature; 
            } 
            set 
            {
                this.feature = value;
                onPropertyChanged("Feature");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Format")]
        public List<string> Format 
        { 
            get 
            {
                return this.format; 
            } 
            set 
            {
                this.format = value;
                onPropertyChanged("Format");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Genre")]
        public string Genre 
        { 
            get 
            {
                return this.genre; 
            } 
            set 
            {
                this.genre = value;
                onPropertyChanged("Genre");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("HardwarePlatform")]
        public string HardwarePlatform 
        { 
            get 
            {
                return this.hardwarePlatform; 
            } 
            set 
            {
                this.hardwarePlatform = value;
                onPropertyChanged("HardwarePlatform");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("HazardousMaterialType")]
        public string HazardousMaterialType 
        { 
            get 
            {
                return this.hazardousMaterialType; 
            } 
            set 
            {
                this.hazardousMaterialType = value;
                onPropertyChanged("HazardousMaterialType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("IsAdultProduct")]
        public bool? IsAdultProduct 
        { 
            get 
            {
                return this.isAdultProduct; 
            } 
            set 
            {
                this.isAdultProduct = value;
                onPropertyChanged("IsAdultProduct");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("IsAutographed")]
        public bool? IsAutographed 
        { 
            get 
            {
                return this.isAutographed; 
            } 
            set 
            {
                this.isAutographed = value;
                onPropertyChanged("IsAutographed");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ISBN")]
        public string ISBN 
        { 
            get 
            {
                return this.iSBN; 
            } 
            set 
            {
                this.iSBN = value;
                onPropertyChanged("ISBN");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("IsEligibleForTradeIn")]
        public bool? IsEligibleForTradeIn 
        { 
            get 
            {
                return this.isEligibleForTradeIn; 
            } 
            set 
            {
                this.isEligibleForTradeIn = value;
                onPropertyChanged("IsEligibleForTradeIn");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("IsMemorabilia")]
        public bool? IsMemorabilia 
        { 
            get 
            {
                return this.isMemorabilia; 
            } 
            set 
            {
                this.isMemorabilia = value;
                onPropertyChanged("IsMemorabilia");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("IssuesPerYear")]
        public string IssuesPerYear 
        { 
            get 
            {
                return this.issuesPerYear; 
            } 
            set 
            {
                this.issuesPerYear = value;
                onPropertyChanged("IssuesPerYear");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ItemPartNumber")]
        public string ItemPartNumber 
        { 
            get 
            {
                return this.itemPartNumber; 
            } 
            set 
            {
                this.itemPartNumber = value;
                onPropertyChanged("ItemPartNumber");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Label")]
        public string Label 
        { 
            get 
            {
                return this.label; 
            } 
            set 
            {
                this.label = value;
                onPropertyChanged("Label");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("LegalDisclaimer")]
        public string LegalDisclaimer 
        { 
            get 
            {
                return this.legalDisclaimer; 
            } 
            set 
            {
                this.legalDisclaimer = value;
                onPropertyChanged("LegalDisclaimer");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ListPrice")]
        public Models.PriceModel ListPrice 
        { 
            get 
            {
                return this.listPrice; 
            } 
            set 
            {
                this.listPrice = value;
                onPropertyChanged("ListPrice");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("MagazineType")]
        public string MagazineType 
        { 
            get 
            {
                return this.magazineType; 
            } 
            set 
            {
                this.magazineType = value;
                onPropertyChanged("MagazineType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Manufacturer")]
        public string Manufacturer 
        { 
            get 
            {
                return this.manufacturer; 
            } 
            set 
            {
                this.manufacturer = value;
                onPropertyChanged("Manufacturer");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ManufacturerMaximumAge")]
        public Models.DecimalWithUnitsModel ManufacturerMaximumAge 
        { 
            get 
            {
                return this.manufacturerMaximumAge; 
            } 
            set 
            {
                this.manufacturerMaximumAge = value;
                onPropertyChanged("ManufacturerMaximumAge");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ManufacturerMinimumAge")]
        public Models.DecimalWithUnitsModel ManufacturerMinimumAge 
        { 
            get 
            {
                return this.manufacturerMinimumAge; 
            } 
            set 
            {
                this.manufacturerMinimumAge = value;
                onPropertyChanged("ManufacturerMinimumAge");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ManufacturerPartsWarrantyDescription")]
        public string ManufacturerPartsWarrantyDescription 
        { 
            get 
            {
                return this.manufacturerPartsWarrantyDescription; 
            } 
            set 
            {
                this.manufacturerPartsWarrantyDescription = value;
                onPropertyChanged("ManufacturerPartsWarrantyDescription");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("MediaType")]
        public string MediaType 
        { 
            get 
            {
                return this.mediaType; 
            } 
            set 
            {
                this.mediaType = value;
                onPropertyChanged("MediaType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Model")]
        public string Model 
        { 
            get 
            {
                return this.model; 
            } 
            set 
            {
                this.model = value;
                onPropertyChanged("Model");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ModelYear")]
        public int? ModelYear 
        { 
            get 
            {
                return this.modelYear; 
            } 
            set 
            {
                this.modelYear = value;
                onPropertyChanged("ModelYear");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("MPN")]
        public string MPN 
        { 
            get 
            {
                return this.mPN; 
            } 
            set 
            {
                this.mPN = value;
                onPropertyChanged("MPN");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("NumberOfDiscs")]
        public int? NumberOfDiscs 
        { 
            get 
            {
                return this.numberOfDiscs; 
            } 
            set 
            {
                this.numberOfDiscs = value;
                onPropertyChanged("NumberOfDiscs");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("NumberOfIssues")]
        public int? NumberOfIssues 
        { 
            get 
            {
                return this.numberOfIssues; 
            } 
            set 
            {
                this.numberOfIssues = value;
                onPropertyChanged("NumberOfIssues");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("NumberOfItems")]
        public int? NumberOfItems 
        { 
            get 
            {
                return this.numberOfItems; 
            } 
            set 
            {
                this.numberOfItems = value;
                onPropertyChanged("NumberOfItems");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("NumberOfPages")]
        public int? NumberOfPages 
        { 
            get 
            {
                return this.numberOfPages; 
            } 
            set 
            {
                this.numberOfPages = value;
                onPropertyChanged("NumberOfPages");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("NumberOfTracks")]
        public int? NumberOfTracks 
        { 
            get 
            {
                return this.numberOfTracks; 
            } 
            set 
            {
                this.numberOfTracks = value;
                onPropertyChanged("NumberOfTracks");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("OperatingSystem")]
        public string OperatingSystem 
        { 
            get 
            {
                return this.operatingSystem; 
            } 
            set 
            {
                this.operatingSystem = value;
                onPropertyChanged("OperatingSystem");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("PackageQuantity")]
        public int? PackageQuantity 
        { 
            get 
            {
                return this.packageQuantity; 
            } 
            set 
            {
                this.packageQuantity = value;
                onPropertyChanged("PackageQuantity");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("PartNumber")]
        public string PartNumber 
        { 
            get 
            {
                return this.partNumber; 
            } 
            set 
            {
                this.partNumber = value;
                onPropertyChanged("PartNumber");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("PictureFormat")]
        public List<string> PictureFormat 
        { 
            get 
            {
                return this.pictureFormat; 
            } 
            set 
            {
                this.pictureFormat = value;
                onPropertyChanged("PictureFormat");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Platform")]
        public List<string> Platform 
        { 
            get 
            {
                return this.platform; 
            } 
            set 
            {
                this.platform = value;
                onPropertyChanged("Platform");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ProductGroup")]
        public string ProductGroup 
        { 
            get 
            {
                return this.productGroup; 
            } 
            set 
            {
                this.productGroup = value;
                onPropertyChanged("ProductGroup");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ProductTypeName")]
        public string ProductTypeName 
        { 
            get 
            {
                return this.productTypeName; 
            } 
            set 
            {
                this.productTypeName = value;
                onPropertyChanged("ProductTypeName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ProductTypeSubcategory")]
        public string ProductTypeSubcategory 
        { 
            get 
            {
                return this.productTypeSubcategory; 
            } 
            set 
            {
                this.productTypeSubcategory = value;
                onPropertyChanged("ProductTypeSubcategory");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("PublicationDate")]
        public string PublicationDate 
        { 
            get 
            {
                return this.publicationDate; 
            } 
            set 
            {
                this.publicationDate = value;
                onPropertyChanged("PublicationDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Publisher")]
        public string Publisher 
        { 
            get 
            {
                return this.publisher; 
            } 
            set 
            {
                this.publisher = value;
                onPropertyChanged("Publisher");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("RegionCode")]
        public string RegionCode 
        { 
            get 
            {
                return this.regionCode; 
            } 
            set 
            {
                this.regionCode = value;
                onPropertyChanged("RegionCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ReleaseDate")]
        public string ReleaseDate 
        { 
            get 
            {
                return this.releaseDate; 
            } 
            set 
            {
                this.releaseDate = value;
                onPropertyChanged("ReleaseDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SeasonSequence")]
        public string SeasonSequence 
        { 
            get 
            {
                return this.seasonSequence; 
            } 
            set 
            {
                this.seasonSequence = value;
                onPropertyChanged("SeasonSequence");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("RunningTime")]
        public Models.DecimalWithUnitsModel RunningTime 
        { 
            get 
            {
                return this.runningTime; 
            } 
            set 
            {
                this.runningTime = value;
                onPropertyChanged("RunningTime");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SeikodoProductCode")]
        public string SeikodoProductCode 
        { 
            get 
            {
                return this.seikodoProductCode; 
            } 
            set 
            {
                this.seikodoProductCode = value;
                onPropertyChanged("SeikodoProductCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Size")]
        public string Size 
        { 
            get 
            {
                return this.size; 
            } 
            set 
            {
                this.size = value;
                onPropertyChanged("Size");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SKU")]
        public string SKU 
        { 
            get 
            {
                return this.sKU; 
            } 
            set 
            {
                this.sKU = value;
                onPropertyChanged("SKU");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Studio")]
        public string Studio 
        { 
            get 
            {
                return this.studio; 
            } 
            set 
            {
                this.studio = value;
                onPropertyChanged("Studio");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SubscriptionLength")]
        public Models.NonNegativeIntegerWithUnitsModel SubscriptionLength 
        { 
            get 
            {
                return this.subscriptionLength; 
            } 
            set 
            {
                this.subscriptionLength = value;
                onPropertyChanged("SubscriptionLength");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Title")]
        public string Title 
        { 
            get 
            {
                return this.title; 
            } 
            set 
            {
                this.title = value;
                onPropertyChanged("Title");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("TrackSequence")]
        public string TrackSequence 
        { 
            get 
            {
                return this.trackSequence; 
            } 
            set 
            {
                this.trackSequence = value;
                onPropertyChanged("TrackSequence");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("TradeInValue")]
        public Models.PriceModel TradeInValue 
        { 
            get 
            {
                return this.tradeInValue; 
            } 
            set 
            {
                this.tradeInValue = value;
                onPropertyChanged("TradeInValue");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("UPC")]
        public string UPC 
        { 
            get 
            {
                return this.uPC; 
            } 
            set 
            {
                this.uPC = value;
                onPropertyChanged("UPC");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Warranty")]
        public string Warranty 
        { 
            get 
            {
                return this.warranty; 
            } 
            set 
            {
                this.warranty = value;
                onPropertyChanged("Warranty");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("WEEETaxValue")]
        public Models.PriceModel WEEETaxValue 
        { 
            get 
            {
                return this.wEEETaxValue; 
            } 
            set 
            {
                this.wEEETaxValue = value;
                onPropertyChanged("WEEETaxValue");
            }
        }
    }
} 