/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class ItemModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string aSIN;
        private string offerListingId;
        private int? quantity;
        private string associateTag;
        private string listItemId;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ASIN")]
        public string ASIN 
        { 
            get 
            {
                return this.aSIN; 
            } 
            set 
            {
                this.aSIN = value;
                onPropertyChanged("ASIN");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("OfferListingId")]
        public string OfferListingId 
        { 
            get 
            {
                return this.offerListingId; 
            } 
            set 
            {
                this.offerListingId = value;
                onPropertyChanged("OfferListingId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Quantity")]
        public int? Quantity 
        { 
            get 
            {
                return this.quantity; 
            } 
            set 
            {
                this.quantity = value;
                onPropertyChanged("Quantity");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("AssociateTag")]
        public string AssociateTag 
        { 
            get 
            {
                return this.associateTag; 
            } 
            set 
            {
                this.associateTag = value;
                onPropertyChanged("AssociateTag");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ListItemId")]
        public string ListItemId 
        { 
            get 
            {
                return this.listItemId; 
            } 
            set 
            {
                this.listItemId = value;
                onPropertyChanged("ListItemId");
            }
        }
    }
} 