/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class LoyaltyPointsModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int? points;
        private Models.PriceModel typicalRedemptionValue;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Points")]
        public int? Points 
        { 
            get 
            {
                return this.points; 
            } 
            set 
            {
                this.points = value;
                onPropertyChanged("Points");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("TypicalRedemptionValue")]
        public Models.PriceModel TypicalRedemptionValue 
        { 
            get 
            {
                return this.typicalRedemptionValue; 
            } 
            set 
            {
                this.typicalRedemptionValue = value;
                onPropertyChanged("TypicalRedemptionValue");
            }
        }
    }
} 