/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class MetaDataModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.KeyValuePairModel keyValuePair;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("KeyValuePair")]
        public Models.KeyValuePairModel KeyValuePair 
        { 
            get 
            {
                return this.keyValuePair; 
            } 
            set 
            {
                this.keyValuePair = value;
                onPropertyChanged("KeyValuePair");
            }
        }
    }
} 