/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class OfferModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.MerchantModel merchant;
        private Models.OfferAttributesModel offerAttributes;
        private List<Models.OfferListingModel> offerListing;
        private Models.LoyaltyPointsModel loyaltyPoints;
        private Models.PromotionsModel promotions;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Merchant")]
        public Models.MerchantModel Merchant 
        { 
            get 
            {
                return this.merchant; 
            } 
            set 
            {
                this.merchant = value;
                onPropertyChanged("Merchant");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("OfferAttributes")]
        public Models.OfferAttributesModel OfferAttributes 
        { 
            get 
            {
                return this.offerAttributes; 
            } 
            set 
            {
                this.offerAttributes = value;
                onPropertyChanged("OfferAttributes");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("OfferListing")]
        public List<Models.OfferListingModel> OfferListing 
        { 
            get 
            {
                return this.offerListing; 
            } 
            set 
            {
                this.offerListing = value;
                onPropertyChanged("OfferListing");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("LoyaltyPoints")]
        public Models.LoyaltyPointsModel LoyaltyPoints 
        { 
            get 
            {
                return this.loyaltyPoints; 
            } 
            set 
            {
                this.loyaltyPoints = value;
                onPropertyChanged("LoyaltyPoints");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Promotions")]
        public Models.PromotionsModel Promotions 
        { 
            get 
            {
                return this.promotions; 
            } 
            set 
            {
                this.promotions = value;
                onPropertyChanged("Promotions");
            }
        }
    }
} 