/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class OffersModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int? totalOffers;
        private int? totalOfferPages;
        private string moreOffersUrl;
        private List<Models.OfferModel> offer;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("TotalOffers")]
        public int? TotalOffers 
        { 
            get 
            {
                return this.totalOffers; 
            } 
            set 
            {
                this.totalOffers = value;
                onPropertyChanged("TotalOffers");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("TotalOfferPages")]
        public int? TotalOfferPages 
        { 
            get 
            {
                return this.totalOfferPages; 
            } 
            set 
            {
                this.totalOfferPages = value;
                onPropertyChanged("TotalOfferPages");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("MoreOffersUrl")]
        public string MoreOffersUrl 
        { 
            get 
            {
                return this.moreOffersUrl; 
            } 
            set 
            {
                this.moreOffersUrl = value;
                onPropertyChanged("MoreOffersUrl");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Offer")]
        public List<Models.OfferModel> Offer 
        { 
            get 
            {
                return this.offer; 
            } 
            set 
            {
                this.offer = value;
                onPropertyChanged("Offer");
            }
        }
    }
} 