/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class PromotionsModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private List<Models.PromotionModel> promotion;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Promotion")]
        public List<Models.PromotionModel> Promotion 
        { 
            get 
            {
                return this.promotion; 
            } 
            set 
            {
                this.promotion = value;
                onPropertyChanged("Promotion");
            }
        }
    }
} 