/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;

namespace AWSECommerceService.PCL.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum RelationshipEnum
    {
        PARENTS, //TODO: Write general description for this method
        CHILDREN, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type RelationshipEnum
    /// </summary>
    public static class RelationshipEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "Parents", "Children" };

        /// <summary>
        /// Converts a RelationshipEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The RelationshipEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(RelationshipEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case RelationshipEnum.PARENTS:
                case RelationshipEnum.CHILDREN:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of RelationshipEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of RelationshipEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<RelationshipEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into RelationshipEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed RelationshipEnum value</returns>
        public static RelationshipEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type RelationshipEnum", value));

            return (RelationshipEnum) index;
        }
    }
} 