/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class RelatedItemsModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.RelationshipEnum relationship;
        private string relationshipType;
        private int? relatedItemCount;
        private int? relatedItemPageCount;
        private int? relatedItemPage;
        private List<Models.RelatedItemModel> relatedItem;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Relationship", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.RelationshipEnum Relationship 
        { 
            get 
            {
                return this.relationship; 
            } 
            set 
            {
                this.relationship = value;
                onPropertyChanged("Relationship");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("RelationshipType")]
        public string RelationshipType 
        { 
            get 
            {
                return this.relationshipType; 
            } 
            set 
            {
                this.relationshipType = value;
                onPropertyChanged("RelationshipType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("RelatedItemCount")]
        public int? RelatedItemCount 
        { 
            get 
            {
                return this.relatedItemCount; 
            } 
            set 
            {
                this.relatedItemCount = value;
                onPropertyChanged("RelatedItemCount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("RelatedItemPageCount")]
        public int? RelatedItemPageCount 
        { 
            get 
            {
                return this.relatedItemPageCount; 
            } 
            set 
            {
                this.relatedItemPageCount = value;
                onPropertyChanged("RelatedItemPageCount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("RelatedItemPage")]
        public int? RelatedItemPage 
        { 
            get 
            {
                return this.relatedItemPage; 
            } 
            set 
            {
                this.relatedItemPage = value;
                onPropertyChanged("RelatedItemPage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("RelatedItem")]
        public List<Models.RelatedItemModel> RelatedItem 
        { 
            get 
            {
                return this.relatedItem; 
            } 
            set 
            {
                this.relatedItem = value;
                onPropertyChanged("RelatedItem");
            }
        }
    }
} 