/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class RentalListingModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.PriceModel price;
        private Models.NonNegativeIntegerWithUnitsModel period;
        private bool? isFulfilledByAmazon;
        private string disclaimer;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Price")]
        public Models.PriceModel Price 
        { 
            get 
            {
                return this.price; 
            } 
            set 
            {
                this.price = value;
                onPropertyChanged("Price");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Period")]
        public Models.NonNegativeIntegerWithUnitsModel Period 
        { 
            get 
            {
                return this.period; 
            } 
            set 
            {
                this.period = value;
                onPropertyChanged("Period");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("IsFulfilledByAmazon")]
        public bool? IsFulfilledByAmazon 
        { 
            get 
            {
                return this.isFulfilledByAmazon; 
            } 
            set 
            {
                this.isFulfilledByAmazon = value;
                onPropertyChanged("IsFulfilledByAmazon");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Disclaimer")]
        public string Disclaimer 
        { 
            get 
            {
                return this.disclaimer; 
            } 
            set 
            {
                this.disclaimer = value;
                onPropertyChanged("Disclaimer");
            }
        }
    }
} 