/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class RentalOfferModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.MerchantModel merchant;
        private List<Models.RentalListingModel> rentalListing;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Merchant")]
        public Models.MerchantModel Merchant 
        { 
            get 
            {
                return this.merchant; 
            } 
            set 
            {
                this.merchant = value;
                onPropertyChanged("Merchant");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("RentalListing")]
        public List<Models.RentalListingModel> RentalListing 
        { 
            get 
            {
                return this.rentalListing; 
            } 
            set 
            {
                this.rentalListing = value;
                onPropertyChanged("RentalListing");
            }
        }
    }
} 