/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class RequestModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.BrowseNodeLookupRequestModel browseNodeLookupRequest;
        private Models.ItemSearchRequestModel itemSearchRequest;
        private Models.ItemLookupRequestModel itemLookupRequest;
        private Models.SimilarityLookupRequestModel similarityLookupRequest;
        private Models.CartGetRequestModel cartGetRequest;
        private Models.CartAddRequestModel cartAddRequest;
        private Models.CartCreateRequestModel cartCreateRequest;
        private Models.CartModifyRequestModel cartModifyRequest;
        private Models.CartClearRequestModel cartClearRequest;
        private Models.ErrorsModel errors;
        private string isValid;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BrowseNodeLookupRequest")]
        public Models.BrowseNodeLookupRequestModel BrowseNodeLookupRequest 
        { 
            get 
            {
                return this.browseNodeLookupRequest; 
            } 
            set 
            {
                this.browseNodeLookupRequest = value;
                onPropertyChanged("BrowseNodeLookupRequest");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ItemSearchRequest")]
        public Models.ItemSearchRequestModel ItemSearchRequest 
        { 
            get 
            {
                return this.itemSearchRequest; 
            } 
            set 
            {
                this.itemSearchRequest = value;
                onPropertyChanged("ItemSearchRequest");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ItemLookupRequest")]
        public Models.ItemLookupRequestModel ItemLookupRequest 
        { 
            get 
            {
                return this.itemLookupRequest; 
            } 
            set 
            {
                this.itemLookupRequest = value;
                onPropertyChanged("ItemLookupRequest");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SimilarityLookupRequest")]
        public Models.SimilarityLookupRequestModel SimilarityLookupRequest 
        { 
            get 
            {
                return this.similarityLookupRequest; 
            } 
            set 
            {
                this.similarityLookupRequest = value;
                onPropertyChanged("SimilarityLookupRequest");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CartGetRequest")]
        public Models.CartGetRequestModel CartGetRequest 
        { 
            get 
            {
                return this.cartGetRequest; 
            } 
            set 
            {
                this.cartGetRequest = value;
                onPropertyChanged("CartGetRequest");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CartAddRequest")]
        public Models.CartAddRequestModel CartAddRequest 
        { 
            get 
            {
                return this.cartAddRequest; 
            } 
            set 
            {
                this.cartAddRequest = value;
                onPropertyChanged("CartAddRequest");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CartCreateRequest")]
        public Models.CartCreateRequestModel CartCreateRequest 
        { 
            get 
            {
                return this.cartCreateRequest; 
            } 
            set 
            {
                this.cartCreateRequest = value;
                onPropertyChanged("CartCreateRequest");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CartModifyRequest")]
        public Models.CartModifyRequestModel CartModifyRequest 
        { 
            get 
            {
                return this.cartModifyRequest; 
            } 
            set 
            {
                this.cartModifyRequest = value;
                onPropertyChanged("CartModifyRequest");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CartClearRequest")]
        public Models.CartClearRequestModel CartClearRequest 
        { 
            get 
            {
                return this.cartClearRequest; 
            } 
            set 
            {
                this.cartClearRequest = value;
                onPropertyChanged("CartClearRequest");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Errors")]
        public Models.ErrorsModel Errors 
        { 
            get 
            {
                return this.errors; 
            } 
            set 
            {
                this.errors = value;
                onPropertyChanged("Errors");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("IsValid")]
        public string IsValid 
        { 
            get 
            {
                return this.isValid; 
            } 
            set 
            {
                this.isValid = value;
                onPropertyChanged("IsValid");
            }
        }
    }
} 