/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;

namespace AWSECommerceService.PCL.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum SimilarityTypeEnum
    {
        INTERSECTION, //TODO: Write general description for this method
        RANDOM, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type SimilarityTypeEnum
    /// </summary>
    public static class SimilarityTypeEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "Intersection", "Random" };

        /// <summary>
        /// Converts a SimilarityTypeEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The SimilarityTypeEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(SimilarityTypeEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case SimilarityTypeEnum.INTERSECTION:
                case SimilarityTypeEnum.RANDOM:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of SimilarityTypeEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of SimilarityTypeEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<SimilarityTypeEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into SimilarityTypeEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed SimilarityTypeEnum value</returns>
        public static SimilarityTypeEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type SimilarityTypeEnum", value));

            return (SimilarityTypeEnum) index;
        }
    }
} 