/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class SimilarityLookupRequestModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.ConditionEnum condition;
        private Models.SimilarityTypeEnum similarityType;
        private List<string> itemId;
        private string merchantId;
        private List<string> responseGroup;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Condition", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.ConditionEnum Condition 
        { 
            get 
            {
                return this.condition; 
            } 
            set 
            {
                this.condition = value;
                onPropertyChanged("Condition");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SimilarityType", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.SimilarityTypeEnum SimilarityType 
        { 
            get 
            {
                return this.similarityType; 
            } 
            set 
            {
                this.similarityType = value;
                onPropertyChanged("SimilarityType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ItemId")]
        public List<string> ItemId 
        { 
            get 
            {
                return this.itemId; 
            } 
            set 
            {
                this.itemId = value;
                onPropertyChanged("ItemId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("MerchantId")]
        public string MerchantId 
        { 
            get 
            {
                return this.merchantId; 
            } 
            set 
            {
                this.merchantId = value;
                onPropertyChanged("MerchantId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ResponseGroup")]
        public List<string> ResponseGroup 
        { 
            get 
            {
                return this.responseGroup; 
            } 
            set 
            {
                this.responseGroup = value;
                onPropertyChanged("ResponseGroup");
            }
        }
    }
} 