/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class TopItemModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string aSIN;
        private string title;
        private string detailPageURL;
        private string productGroup;
        private List<string> author;
        private List<string> artist;
        private List<string> actor;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ASIN")]
        public string ASIN 
        { 
            get 
            {
                return this.aSIN; 
            } 
            set 
            {
                this.aSIN = value;
                onPropertyChanged("ASIN");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Title")]
        public string Title 
        { 
            get 
            {
                return this.title; 
            } 
            set 
            {
                this.title = value;
                onPropertyChanged("Title");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("DetailPageURL")]
        public string DetailPageURL 
        { 
            get 
            {
                return this.detailPageURL; 
            } 
            set 
            {
                this.detailPageURL = value;
                onPropertyChanged("DetailPageURL");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ProductGroup")]
        public string ProductGroup 
        { 
            get 
            {
                return this.productGroup; 
            } 
            set 
            {
                this.productGroup = value;
                onPropertyChanged("ProductGroup");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Author")]
        public List<string> Author 
        { 
            get 
            {
                return this.author; 
            } 
            set 
            {
                this.author = value;
                onPropertyChanged("Author");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Artist")]
        public List<string> Artist 
        { 
            get 
            {
                return this.artist; 
            } 
            set 
            {
                this.artist = value;
                onPropertyChanged("Artist");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Actor")]
        public List<string> Actor 
        { 
            get 
            {
                return this.actor; 
            } 
            set 
            {
                this.actor = value;
                onPropertyChanged("Actor");
            }
        }
    }
} 