/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class TopSellersModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.TopSellerModel topSeller;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("TopSeller")]
        public Models.TopSellerModel TopSeller 
        { 
            get 
            {
                return this.topSeller; 
            } 
            set 
            {
                this.topSeller = value;
                onPropertyChanged("TopSeller");
            }
        }
    }
} 