/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class VariationsModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.ItemModel item;
        private int? totalVariations;
        private int? totalVariationPages;
        private Models.VariationDimensionsModel variationDimensions;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Item")]
        public Models.ItemModel Item 
        { 
            get 
            {
                return this.item; 
            } 
            set 
            {
                this.item = value;
                onPropertyChanged("Item");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("TotalVariations")]
        public int? TotalVariations 
        { 
            get 
            {
                return this.totalVariations; 
            } 
            set 
            {
                this.totalVariations = value;
                onPropertyChanged("TotalVariations");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("TotalVariationPages")]
        public int? TotalVariationPages 
        { 
            get 
            {
                return this.totalVariationPages; 
            } 
            set 
            {
                this.totalVariationPages = value;
                onPropertyChanged("TotalVariationPages");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("VariationDimensions")]
        public Models.VariationDimensionsModel VariationDimensions 
        { 
            get 
            {
                return this.variationDimensions; 
            } 
            set 
            {
                this.variationDimensions = value;
                onPropertyChanged("VariationDimensions");
            }
        }
    }
} 