/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class VariationSummaryModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.PriceModel lowestPrice;
        private Models.PriceModel highestPrice;
        private Models.PriceModel lowestSalePrice;
        private Models.PriceModel highestSalePrice;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("LowestPrice")]
        public Models.PriceModel LowestPrice 
        { 
            get 
            {
                return this.lowestPrice; 
            } 
            set 
            {
                this.lowestPrice = value;
                onPropertyChanged("LowestPrice");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("HighestPrice")]
        public Models.PriceModel HighestPrice 
        { 
            get 
            {
                return this.highestPrice; 
            } 
            set 
            {
                this.highestPrice = value;
                onPropertyChanged("HighestPrice");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("LowestSalePrice")]
        public Models.PriceModel LowestSalePrice 
        { 
            get 
            {
                return this.lowestSalePrice; 
            } 
            set 
            {
                this.lowestSalePrice = value;
                onPropertyChanged("LowestSalePrice");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("HighestSalePrice")]
        public Models.PriceModel HighestSalePrice 
        { 
            get 
            {
                return this.highestSalePrice; 
            } 
            set 
            {
                this.highestSalePrice = value;
                onPropertyChanged("HighestSalePrice");
            }
        }
    }
} 