/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace AWSECommerceService.PCL.Models
{
    public class VariationDimensionsModel : BaseModel 
    {
        // These fields hold the values for the public properties.
        private List<string> variationDimension;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("VariationDimension")]
        public List<string> VariationDimension 
        { 
            get 
            {
                return this.variationDimension; 
            } 
            set 
            {
                this.variationDimension = value;
                onPropertyChanged("VariationDimension");
            }
        }
    }
} 