/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using AWSECommerceService.PCL.Controllers;
using APIMATIC.SDK.Http.Client;
using APIMATIC.SDK.Common;

namespace AWSECommerceService.PCL
{
    public partial class AWSECommerceServiceClient: IAWSECommerceServiceClient
    {

        /// <summary>
        /// Singleton access to AWSECommerceServiceBinding controller
        /// </summary>
        public IAWSECommerceServiceBindingController AWSECommerceServiceBinding
        {
            get
            {
                return AWSECommerceServiceBindingController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public AWSECommerceServiceClient() { }

        /// <summary>
        /// Client initialization constructor
        /// </summary>
        public AWSECommerceServiceClient(string aFIeyt, string b, string c, string oAuthAccessToken)
        {
            Configuration.AFIeyt = aFIeyt;
            Configuration.B = b;
            Configuration.C = c;
            Configuration.OAuthAccessToken = oAuthAccessToken;
        }
        #endregion
    }
}