/*
 * AWSECommerceService.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using AWSECommerceService.PCL.Controllers;

namespace AWSECommerceService.PCL
{
    public partial interface IAWSECommerceServiceClient
    {

        /// <summary>
        /// Singleton access to AWSECommerceServiceBinding controller
        /// </summary>
        IAWSECommerceServiceBindingController AWSECommerceServiceBinding { get;}

    }
}